export default {
	weapons: {
		rifles: [
			'M4',
			'SCAR',
			'AK47',
			'G36',
			'AR15',
			'M16',
			'HK416',
			'ACR',
			'AK12',
			'AK74',
			'AK74U',
			'AR 9mm',
			'AR .556',
			'AR .308',
			'AS Val',
			'AUG',
			'CZ 805',
			'FAMAS',
			'FAL',
			'FNC',
			'G3',
			'Galil',
			'HK33',
			'L1A1',
			'L85',
			'M1 Garand',
			'M14',
			'Magpul PDR',
			'SA80',
			'Scorpion EVO 3',
			'SG553',
			'SL8',
			'SR-25',
			'TAR-21',
			'TK-45',
			'Type 56',
			'Type 64',
			'Type 89',
			'Type 95',
			'Type 97',
			'UAR',
			'VZ.58'
		],
		smgs: [
			'MP5',
			'MP7',
			'MP9',
			'UMP45',
			'UMP9',
			'Vector',
			'MAC-10',
			'M1938',
			'M3A1 Grease Gun',
			'MP40',
			'PP-19 Bizon',
			'P90',
			'PPSH 41',
			'Scorpion',
			'Sterling',
			'Thompson',
			'Vityaz-SN'
		],
		snipers: [
			'ASW338LM',
			'Barret .50',
			'Kar98K',
			'L96',
			'M1873',
			'M1903',
			'M24',
			'M40',
			'MB44',
			'STRIKER',
			'SVD',
			'VSR'
		],
		shotguns: ['AA-12', 'Benelli M4', 'KSG', 'M1014', 'M870', 'SAS-12', 'SPAS-12', 'STF-12'],
		pistols: [
			'G17',
			'G18',
			'G19',
			'1911',
			'Hi-Capa',
			'M9',
			'CZ 45',
			'CZ P-09',
			'CZ Shadow 2',
			'Desert Eagle',
			'F226',
			'F228',
			'Five-Seven',
			'HK45',
			'Luger',
			'Revolver',
			'M93R',
			'M&P',
			'Makarov',
			'MK23 Socom',
			'P14',
			'P226',
			'PX4',
			'TT-33',
			'USP',
			'XDM',
			'XP18'
		],
		support: ['M249', 'MG42', 'PKP', 'Trident LMG', 'Stoner', 'ZB26'],
		launchers: ['Bazooka', 'GL06', 'GLM', 'M052', 'M79', 'RPG-7']
	},
	gear: {
		protection: ['Glasses', 'Goggles', 'Fast Helmet', 'Full Face Helmet', 'Half Face Mask', 'Shemagh', 'Knee Pads', 'Elbow Pads'],
		carriers: ['Chest Rig', 'Plate Carrier', 'Belt'],
		grenades: ['TRMR', 'Storm 360', 'Pyro/Strike', 'Claymore'],
		holsters: ['Leg Holster', 'Retention Holster', 'Scabbard', 'Sling'],
		communication: ['Radio', 'Headset'],
		misc: ['GoPro', 'Knife']
	},
	attachments: {
		sights: ['Red Dot', 'Reflex', 'Holographic', 'Telescopic', 'Iron Sights'],
		barrel: ['Surpressor', 'Flash Hider', 'Tracer Unit'],
		illumination: ['Pistol Torch', 'Flashlight', 'PEQ Box'],
		underbarrel: ['Vertical Foregrip', 'Angled Foregrip', 'Bipod', 'Grenade Launcher']
	}
}
